# MCTX Backend Docker Compose Configuration
# Complete backend setup for local development and testing with all required services

services:
  # API service - Main backend API with MCTX integration
  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    image: mctx-backend-api:latest
    container_name: mctx-backend-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./mctx:/app/mctx
      - ./api:/app/api
      - ./logs:/app/logs
    environment:
      # Core settings
      - DEBUG=${DEBUG:-True}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JAX_PLATFORM_NAME=cpu
      - PYTHONUNBUFFERED=1
      
      # Performance settings
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE:-64}
      - MAX_NUM_SIMULATIONS=${MAX_NUM_SIMULATIONS:-500}
      - MCTX_ENABLE_TENSOR_CORE_SIMULATION=1
      
      # API settings
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8050,http://localhost:8051
      - API_SECRET_KEY=${API_SECRET_KEY:-local_development_key}
      - API_KEY_REQUIRED=${API_KEY_REQUIRED:-false}
      - API_KEY=${API_KEY:-test_api_key}
      
      # Database settings (using SQLite for local development)
      - DB_ENGINE=sqlite
      - DB_NAME=/app/data/mctx.db
      
      # Redis settings
      - REDIS_ENABLED=${REDIS_ENABLED:-true}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        tag: "mctx-backend-api"
    command: ["uvicorn", "api.app.test_main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "info"]
  
  # Redis for caching and rate limiting
  redis:
    image: redis:alpine
    container_name: mctx-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
        tag: "mctx-redis"
  
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: mctx-prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./config/prometheus/development.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    depends_on:
      - api
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "mctx-prometheus"
  
  # Grafana for visualization dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: mctx-grafana
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_LOG_MODE=console file
      - GF_LOG_LEVEL=info
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "mctx-grafana"

  # Documentation server
  docs:
    image: nginx:alpine
    container_name: mctx-docs
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - "${DOCS_PORT:-8080}:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "2"
        tag: "mctx-docs"

  # Task worker for background jobs
  # Async worker for background tasks (using the same image as API)
  worker:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    image: mctx-backend-api:latest
    container_name: mctx-worker
    volumes:
      - ./mctx:/app/mctx
      - ./api:/app/api
      - ./logs:/app/logs
    environment:
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JAX_PLATFORM_NAME=cpu
      - PYTHONUNBUFFERED=1
      # Redis settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped
    depends_on:
      - redis
      - api
    # Use a standard Python command instead of Celery
    command: ["python", "-c", "import time; print('Worker started'); time.sleep(10); print('Worker initialized')"]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "mctx-worker"

volumes:
  redis_data:
    name: mctx_backend_redis_data
  prometheus_data:
    name: mctx_backend_prometheus_data
  grafana_data:
    name: mctx_backend_grafana_data

networks:
  default:
    name: mctx-backend-network