version: '3.8'

# DEVELOPMENT COMPOSE FILE
# This is a simplified Docker Compose file for local development.
# For production deployment with NVIDIA GPU support, see:
# ./deployment/docker-compose.yml

services:
  # Basic API service (CPU-only development version)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      - DEBUG=True
      - LOG_LEVEL=INFO
      - JAX_PLATFORM=cpu
      - MAX_BATCH_SIZE=64
      - MAX_NUM_SIMULATIONS=500
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/mcts/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  
  # Simple frontend for development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api/v1
    restart: unless-stopped
    
  # Basic monitoring setup
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana_data: