global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mctx-blue"
    metrics_path: /metrics
    static_configs:
      - targets: ["mctx-blue:8000"]
    scrape_interval: 10s
    labels:
      environment: "blue"

  - job_name: "mctx-green"
    metrics_path: /metrics
    static_configs:
      - targets: ["mctx-green:8000"]
    scrape_interval: 10s
    labels:
      environment: "green"

  - job_name: "vis-blue"
    metrics_path: /metrics
    static_configs:
      - targets: ["vis-blue:8050"]
    scrape_interval: 10s
    labels:
      environment: "blue"

  - job_name: "vis-green"
    metrics_path: /metrics
    static_configs:
      - targets: ["vis-green:8050"]
    scrape_interval: 10s
    labels:
      environment: "green"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 10s