global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]
    scrape_interval: 10s

  - job_name: "visualization"
    metrics_path: /metrics
    static_configs:
      - targets: ["visualization:8050"]
    scrape_interval: 10s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 10s