global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mctx-api"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 10s

  - job_name: "frontend"
    metrics_path: /metrics
    static_configs:
      - targets: ["frontend:80"]
    scrape_interval: 10s