global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mctx-nvidia"
    metrics_path: /metrics
    static_configs:
      - targets: ["mctx-nvidia:8000"]
    scrape_interval: 10s

  - job_name: "mctx-vis"
    metrics_path: /metrics
    static_configs:
      - targets: ["mctx-vis:8050"]
    scrape_interval: 10s