global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mctx-nvidia"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["mctx-nvidia:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "mctx-nvidia"

  - job_name: "mctx-vis"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["mctx-vis:8050"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "mctx-vis"

  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "node"

  - job_name: "dcgm-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["dcgm-exporter:9400"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "gpu"
        
  - job_name: "grafana"
    scrape_interval: 15s
    static_configs:
      - targets: ["grafana:3000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "grafana"

  - job_name: "renderer"
    scrape_interval: 15s
    static_configs:
      - targets: ["renderer:8081"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "renderer"