#!/bin/bash
# Switch active deployment between blue and green

# Check if color argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 [blue|green]"
    exit 1
fi

COLOR=$1

# Validate color
if [ "$COLOR" != "blue" ] && [ "$COLOR" != "green" ]; then
    echo "Invalid color. Use 'blue' or 'green'."
    exit 1
fi

# Create active_deployment.conf file
cat > /etc/nginx/conf.d/active_deployment.conf << EOF
# This file is automatically generated - DO NOT EDIT
# Active deployment: $COLOR

location /api/ {
    proxy_pass http://mctx_api_$COLOR/;
}

location /vis/ {
    proxy_pass http://mctx_vis_$COLOR/;
}
EOF

# Set environment variable
echo "ACTIVE_DEPLOYMENT=$COLOR" > /etc/environment

# Reload NGINX configuration
nginx -s reload

echo "Switched to $COLOR deployment"
exit 0